name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:

    strategy:
      matrix:
        jdk_version: ['11', '17']
        machine: ['ubuntu-latest', 'macos-latest']
        
    runs-on: ${{ matrix.machine }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk_version }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
